# Generated by Django 5.1.6 on 2025-07-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='PaymentAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='PaymentMethod',
            field=models.CharField(default='Cash', max_length=50),
        ),
    ]
