# Generated by Django 3.2.23 on 2025-10-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='FileUploadID',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='FileUpload',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
