# Generated by Django 3.2.23 on 2025-10-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0002_auto_20251027_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
