# Generated by Django 5.1.6 on 2025-07-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0002_uploadfiles_paymentamount_uploadfiles_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='Unique_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
