# Generated by Django 3.2.23 on 2025-10-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0003_otpverification_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='owner_phone_number',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
