# Generated by Django 3.2.23 on 2025-10-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0004_alter_customuser_owner_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='max_attempts',
            field=models.IntegerField(default=5),
        ),
    ]
