# Generated by Django 5.1.6 on 2025-07-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0004_alter_uploadfiles_unique_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='OrderId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
