# Generated by Django 5.1.6 on 2025-10-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0005_uploadfiles_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
