# Generated by Django 3.2.23 on 2025-11-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0005_otpverification_max_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='owner_fullname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='owner_phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='owner_shop_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shop_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(blank=True, default='forgot_password', max_length=50, null=True),
        ),
    ]
