# Generated by Django 3.2.23 on 2025-11-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0006_auto_20251101_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='owner_fullname',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='owner_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='owner_shop_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
