# Generated by Django 5.1.6 on 2025-10-01 12:50

import smartdocx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0006_paymentgateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='FileUpload',
            field=models.FileField(blank=True, null=True, upload_to=smartdocx.models.upload_to_path),
        ),
    ]
