# Generated by Django 5.1.6 on 2025-10-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0007_alter_uploadfiles_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='CustomerName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='FileUpload',
            field=models.FileField(blank=True, null=True, upload_to='uploaded/'),
        ),
    ]
