# Generated by Django 3.2.23 on 2025-11-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0008_weblogintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblogintoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weblogintoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
