# Generated by Django 5.1.6 on 2025-10-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0008_uploadfiles_customername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='PrintStatus',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
