# Generated by Django 5.1.6 on 2025-10-08 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0009_uploadfiles_printstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='Created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
