# Generated by Django 3.2.23 on 2025-11-15 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0009_auto_20251115_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfiles',
            options={'ordering': ['-Created_at']},
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='Binding',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='CustomerName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='FileUpload',
            field=models.TextField(blank=True, help_text='JSON dictionary of filename: file_url', null=True),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='FileUploadID',
            field=models.TextField(blank=True, help_text='JSON dictionary of filename: file_id', null=True),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='OrderId',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='PaperSize',
            field=models.CharField(default='a4', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='PaperType',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='PaymentAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='PaymentMethod',
            field=models.CharField(default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='PaymentStatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='PrintColor',
            field=models.CharField(default='bw', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='PrintSide',
            field=models.CharField(default='single', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='Transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='uploadfiles',
            table='Upload_files',
        ),
    ]
