# Generated by Django 3.2.23 on 2025-11-15 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0010_auto_20251115_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfiles',
            options={'verbose_name_plural': 'Uploaded Files'},
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='Binding',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='CustomerName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='OrderId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='PaperSize',
            field=models.CharField(default='A4', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='PaperType',
            field=models.CharField(default='Portrait', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='PaymentAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='PaymentMethod',
            field=models.CharField(default='Cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='PaymentStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='PrintColor',
            field=models.CharField(default='Color', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='PrintSide',
            field=models.CharField(default='One-sided', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='Transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='uploadfiles',
            table=None,
        ),
    ]
