# Generated by Django 5.2.4 on 2025-10-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0010_uploadfiles_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='FileUpload',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
