# Generated by Django 5.2.4 on 2025-10-18 05:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0011_alter_uploadfiles_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='FileUpload',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='documents'),
        ),
    ]
