# Generated by Django 3.2.23 on 2025-11-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0011_auto_20251115_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfiles',
            options={'ordering': ['-Created_at'], 'verbose_name_plural': 'Uploaded Files'},
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='FileUpload',
            field=models.TextField(blank=True, default='{}', help_text='JSON dictionary of filename: file_url', null=True),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='FileUploadID',
            field=models.TextField(blank=True, default='{}', help_text='JSON dictionary of filename: file_id', null=True),
        ),
    ]
