# Generated by Django 3.2.23 on 2025-11-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0012_auto_20251115_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='FilePagesCount',
            field=models.TextField(blank=True, default='{}', help_text='JSON dictionary of filename: page_count', null=True),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='NoOfPages',
            field=models.IntegerField(default=0, help_text='Total pages across all files'),
        ),
    ]
