# Generated by Django 5.2.4 on 2025-10-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0012_alter_uploadfiles_fileupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfiles',
            options={'verbose_name_plural': 'Uploaded Files'},
        ),
    ]
