# Generated by Django 5.2.4 on 2025-10-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0014_alter_uploadfiles_fileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='FileUpload',
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='FileId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='FileUrl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
