# Generated by Django 5.2.4 on 2025-10-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0015_remove_uploadfiles_fileupload_uploadfiles_fileid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='FileId',
        ),
        migrations.RemoveField(
            model_name='uploadfiles',
            name='FileUrl',
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='FileUpload',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
