# Generated by Django 5.2.4 on 2025-10-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocx', '0016_remove_uploadfiles_fileid_remove_uploadfiles_fileurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='FileUpload',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
